# Generated by Django 3.0.1 on 2019-12-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование характеристики')),
                ('value', models.CharField(max_length=128, verbose_name='Значение характеристики')),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование раздела')),
                ('img', models.ImageField(upload_to='', verbose_name='/upload/sections')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование продукта')),
                ('img', models.ImageField(upload_to='', verbose_name='/upload/product')),
                ('characteristics', models.ManyToManyField(to='catalog.Characteristics')),
                ('sections', models.ManyToManyField(to='catalog.Sections')),
            ],
        ),
    ]
