# Generated by Django 3.0.1 on 2019-12-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristics',
            options={'verbose_name': 'Характеристику', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='sections',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='upload/product', verbose_name='Изображение для продукта'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='img',
            field=models.ImageField(upload_to='upload/sections', verbose_name='Изображение для раздела'),
        ),
    ]
