# Generated by Django 3.0.1 on 2019-12-26 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191227_0232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Characteristics',
            new_name='Characteristic',
        ),
        migrations.RenameModel(
            old_name='Sections',
            new_name='Section',
        ),
    ]
